version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi_container
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_DRIVER: ${DB_DRIVER}
      DB_TYPE: ${DB_TYPE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_OPTIONS: ${DB_OPTIONS}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env

volumes:
  postgres_data:
